#!/system/bin/sh
# ========================================
# init.d script for Android Revolution HD
# for HTC One X and HTC One X+
# ========================================

sleep 60
echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
echo "60" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
echo "30000" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate
log -p i -t ARHD "Ondemand script executed"
