#!/system/bin/sh

# ArchiDroid FirstBoot Script
# JustArchi@JustArchi.net

# Not Disabled
#exit 0

# We don't need to reload anything for now
ADRELOAD=0

# Cool ArchiDroid Banner
#if [ -e /system/bin/boot-dmesg ]; then
#	ADBANNER=1
#else
	ADBANNER=0
#fi

# We want some sqlite3 updates and settings but only if INSTALL mode is enabled
if [ -e /data/media/0/archidroid/INSTALL ]; then
	if [ -d /data/media/0/archidroid/firstboot/settings ]; then
		cd /data/media/0/archidroid/firstboot/settings
		ADMANY=`ls | wc -l`
	fi
	DBUPDATE=1 # We don't want DBUPDATE for now, XXUFME7 doesn't like it
	ADRELOAD=1 # And so we don't need reload as well
elif [ -e /data/media/0/archidroid/UPDATE ]; then
	DBUPDATE=0
	ADMANY=0
else
	# Panic
	exit 1
fi

# ArchiDroid Semaphore
# Wait until we see some android processes to consider boot is more or less complete (credits to AndiP71)
while ! pgrep com.android ; do

	if [ $ADBANNER -eq 1 ]; then
		echo ""
		echo "*******************************************************************************"
		echo "*             _                _      _  ____               _      _          *"
		echo "*            / \    _ __  ___ | |__  (_)|  _ \  _ __  ___  (_)  __| |         *"
		echo "*           / _ \  | '__|/ __|| '_ \ | || | | || '__|/ _ \ | | / _\` |         *"
		echo "*          / ___ \ | |  | (__ | | | || || |_| || |  | (_) || || (_| |         *"
		echo "*         /_/   \_\|_|   \___||_| |_||_||____/ |_|   \___/ |_| \__,_|         *"
		echo "*                                                                             *"
		echo "*******************************************************************************"
		echo "*                  _                       _  _                               *"
		echo "*                 | |     ___    __ _   __| |(_) _ __    __ _                 *"
		echo "*                 | |    / _ \  / _\` | / _\` || || '_ \  / _\` |                *"
		echo "*                 | |___| (_) || (_| || (_| || || | | || (_| |                *"
		echo "*                 |_____|\___/  \__,_| \__,_||_||_| |_| \__, |                *"
		echo "*                                                       |___/                 *"
		echo "*******************************************************************************"
		echo "*            root@ArchiDroid:~# Waiting for ArchiDroid to load...             *"
		echo "*******************************************************************************"
		echo ""
	fi
	
	# Now let's MAKE SURE that our settings are in fact applied, only if we don't have shared_prefs already (prevent non-clean override)
	if [ $ADMANY -gt 0 ]; then
		for FOLDER in * ; do
			if [ -d /data/data/$FOLDER ]; then
				if [ ! -d /data/data/$FOLDER/shared_prefs ]; then
					mv $FOLDER/* /data/data/$FOLDER
					
					# Let's set basic permissions because ArchiDroid_Permfix will fix it anyway really soon
					ADOWNER=`ls -ld /data/data/$FOLDER | awk '{print $3}'`
					chown -hR $ADOWNER.$ADOWNER /data/data/$FOLDER
					chmod -R 755 /data/data/$FOLDER
					
					# And we're done!
					rm -Rf $FOLDER
					ADOWNER=""
					((ADMANY--))
				else
					rm -Rf $FOLDER
					ADOWNER=""
					((ADMANY--))
				fi
			fi
		done
		#ADMANY=`ls | wc -l`
	fi
	
	if [ $DBUPDATE -eq 1 ]; then
		if [ -e /data/data/com.android.providers.settings/databases/settings.db ]; then
			MAKESURE=1
			while [ $MAKESURE -eq 1 ]; do
				MAKESURE=`sqlite3 /data/data/com.android.providers.settings/databases/settings.db "insert into global values(null, 'transition_animation_scale', '0.5');" 2>&1 1>/dev/null | wc -l`
				sleep $MAKESURE
			done
			MAKESURE=1
			while [ $MAKESURE -eq 1 ]; do
				MAKESURE=`sqlite3 /data/data/com.android.providers.settings/databases/settings.db "insert into global values(null, 'animator_duration_scale', '0.5');" 2>&1 1>/dev/null | wc -l`
				sleep $MAKESURE
			done
			MAKESURE=1
			while [ $MAKESURE -eq 1 ]; do
				MAKESURE=`sqlite3 /data/data/com.android.providers.settings/databases/settings.db "insert into global values(null, 'window_animation_scale', '0.5');" 2>&1 1>/dev/null | wc -l`
				sleep $MAKESURE
			done
			MAKESURE=1
			while [ $MAKESURE -eq 1 ]; do
				MAKESURE=`sqlite3 /data/data/com.android.providers.settings/databases/settings.db "insert into global values(null, 'install_non_market_apps', '1');" 2>&1 1>/dev/null | wc -l`
				sleep $MAKESURE
			done
			MAKESURE=1
			while [ $MAKESURE -eq 1 ]; do
				MAKESURE=`sqlite3 /data/data/com.android.providers.settings/databases/settings.db "insert into system values(null, 'lockscreen_ripple_effect', '2');" 2>&1 1>/dev/null | wc -l`
				sleep $MAKESURE
			done

			# And don't execute twice
			DBUPDATE=0
		fi
	fi
	
	
	# Sleeping time
	sleep 2
done

# Now that is checked, let's just wait another tiny little bit
sleep 10

# If we have any more runonce scripts then it's the right place for that


# I'm runonce script so let's clean everything and delete myself

# NOTICE
# ArchiDroid has sysro/sysrw support, change that to remount system rw if needed
rm -f /data/media/0/archidroid/INSTALL
rm -f /data/media/0/archidroid/UPDATE
rm -Rf /data/media/0/archidroid/firstboot
sysrw
rm -f $0
sysro


# Execute hot reboot if we need it
if [ $ADRELOAD -eq 1 ]; then
	sync
	killall system_server
fi

# Finish
exit 0